#!/bin/bash
#-----kiritosshxd------
fun_swap() {
    clear
		echo -e "\E[44;1;37m            จัดการหน่วยความจำเสมือน             \E[0m"
        echo ""
		echo -e "\033[1;31mSwap คือพื้นที่แลกเปลี่ยนที่ใช้เพื่อเพิ่มจำนวน RAM ในระบบ (แนะนำสำหรับเครื่องที่มี RAM น้อย).\033[0m"
        echo -e "\033[1;31mก่อนเปิดใช้งาน ควรทราบก่อนว่าเครื่องของคุณมีพื้นที่เก็บข้อมูลเท่าใด และควรเหลือพื้นที่เก็บข้อมูลไว้ให้เพียงพอเพื่อหลีกเลี่ยงการขัดข้อง.\033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mเปิดใช้งาน SWAP / เปลี่ยนค่า SWAP \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mปิดใช้งานการสลับ\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
		echo ""
		echo -ne "\033[1;32mคุณต้องการทำอะไร? \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m           หน่วยความจำเสมือน              \E[0m"
			echo ""
			echo -ne "\033[1;32mคุณต้องการใช้กี่กิกะบิต \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mกิกะส์ไม่ถูกต้อง!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "\033[1;32mการเริ่มต้นหน่วยความจำเสมือน \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mเปิดใช้งานหน่วยความจำเสมือนสำเร็จแล้ว\033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m            การปิดการใช้งานหน่วยความจำเสมือน              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mปิดใช้งานหน่วยความจำเสมือนสำเร็จแล้ว!\033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mการกลับมา...\033[0m"
			sleep 1
			menu
		else
			echo ""
			echo -e "\033[1;31mตัวเลือกไม่ถูกต้อง !\033[0m"
			sleep 1
			fun_swap
		fi 
}
fun_swap